ensemble:
  file_name: ensemble_submission.csv
  prediction_col: target

  members:
    - name: resnet50
      model_path: configs/model/resnet50.yaml
      output_dir: outputs/resnet50
      weight: 0.8

    - name: convnext_tiny
      model_path: configs/model/convnext_tiny.yaml
      output_dir: outputs/convnext_tiny
      weight: 0.2